name: "Unit tests"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
