name: "Unit tests"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependencies
      - run: yarn ci

  unit-test:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: run unit tests
      - run: yarn test
