name: "Unit tests"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
   
    name: run tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - run: npm ci
      - run: yarn test
