name: "Unit tests"
on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    name: run tests

    
          
            
    

          
          Expand Down
    
    
  
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - run: yarn ci
      - run: yarn test

  # unit-test:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: install node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "18"
  #     - name: Run unit tests
  #       run: yarn test
